### ISSUE TITLE
How to clear TextFiled

### ISSUE THREAD

**Issue by kamalupasena** [meilbn/MLBPasswordTextField#1]
Hi i am using this library in swift 4.0 and when i am trying to clear text using 
`txtOTA.text = ""` or `txtOTA.text = nil`  it's not working. Can you tell me what should i have to do to clear the text

**Comment by meilbn** [comment]
Sorry, I didn't thought about this.
I will update this library soon.

**Comment by meilbn** [comment]
Hi, library is update, if you using CocoaPods, you can update version to ``0.0.5`` to clear text with ``reset`` function.

**Comment by kamalupasena** [comment]
HI Thank you very much for the quick response. reset function working really smooth now thank you

**Comment by meilbn** [comment]
You are welcome.
Sorry for let you waiting two days, I didn't notice emails.
